name: Build and Test .NET Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: |
        cd CarRentApp
        dotnet restore

    - name: Build solution
      run: |
        cd CarRentApp
        dotnet build --configuration Release --no-restore

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies for tests
      run: |
        cd CarRentApp.Tests
        dotnet restore

    - name: Run tests
      run: |
        cd CarRentApp.Tests
        dotnet test --configuration Release --no-restore --verbosity normal
